require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NothingsController do

  # This should return the minimal set of attributes required to create a valid
  # Nothing. As you add validations to Nothing, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "message" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NothingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nothings as @nothings" do
      nothing = Nothing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nothings).should eq([nothing])
    end
  end

  describe "GET show" do
    it "assigns the requested nothing as @nothing" do
      nothing = Nothing.create! valid_attributes
      get :show, {:id => nothing.to_param}, valid_session
      assigns(:nothing).should eq(nothing)
    end
  end

  describe "GET new" do
    it "assigns a new nothing as @nothing" do
      get :new, {}, valid_session
      assigns(:nothing).should be_a_new(Nothing)
    end
  end

  describe "GET edit" do
    it "assigns the requested nothing as @nothing" do
      nothing = Nothing.create! valid_attributes
      get :edit, {:id => nothing.to_param}, valid_session
      assigns(:nothing).should eq(nothing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nothing" do
        expect {
          post :create, {:nothing => valid_attributes}, valid_session
        }.to change(Nothing, :count).by(1)
      end

      it "assigns a newly created nothing as @nothing" do
        post :create, {:nothing => valid_attributes}, valid_session
        assigns(:nothing).should be_a(Nothing)
        assigns(:nothing).should be_persisted
      end

      it "redirects to the created nothing" do
        post :create, {:nothing => valid_attributes}, valid_session
        response.should redirect_to(Nothing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nothing as @nothing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nothing.any_instance.stub(:save).and_return(false)
        post :create, {:nothing => { "message" => "invalid value" }}, valid_session
        assigns(:nothing).should be_a_new(Nothing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nothing.any_instance.stub(:save).and_return(false)
        post :create, {:nothing => { "message" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nothing" do
        nothing = Nothing.create! valid_attributes
        # Assuming there are no other nothings in the database, this
        # specifies that the Nothing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nothing.any_instance.should_receive(:update_attributes).with({ "message" => "MyString" })
        put :update, {:id => nothing.to_param, :nothing => { "message" => "MyString" }}, valid_session
      end

      it "assigns the requested nothing as @nothing" do
        nothing = Nothing.create! valid_attributes
        put :update, {:id => nothing.to_param, :nothing => valid_attributes}, valid_session
        assigns(:nothing).should eq(nothing)
      end

      it "redirects to the nothing" do
        nothing = Nothing.create! valid_attributes
        put :update, {:id => nothing.to_param, :nothing => valid_attributes}, valid_session
        response.should redirect_to(nothing)
      end
    end

    describe "with invalid params" do
      it "assigns the nothing as @nothing" do
        nothing = Nothing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nothing.any_instance.stub(:save).and_return(false)
        put :update, {:id => nothing.to_param, :nothing => { "message" => "invalid value" }}, valid_session
        assigns(:nothing).should eq(nothing)
      end

      it "re-renders the 'edit' template" do
        nothing = Nothing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nothing.any_instance.stub(:save).and_return(false)
        put :update, {:id => nothing.to_param, :nothing => { "message" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nothing" do
      nothing = Nothing.create! valid_attributes
      expect {
        delete :destroy, {:id => nothing.to_param}, valid_session
      }.to change(Nothing, :count).by(-1)
    end

    it "redirects to the nothings list" do
      nothing = Nothing.create! valid_attributes
      delete :destroy, {:id => nothing.to_param}, valid_session
      response.should redirect_to(nothings_url)
    end
  end

end
